### ISSUE TITLE
"create a concatenated string from 0 to 19" with the map function?

### ISSUE THREAD

**Issue by afg984** [kennethreitz/python-guide#531]
In structure.rst: create a concatenated string from 0 to 19 (e.g. "012..1819")

**Best**

```python
# create a concatenated string from 0 to 19 (e.g. "012..1819")
nums = [str(n) for n in range(20)]
print "".join(nums)
```

how about using the following:

```python
"".join(map(str, range(20)))
```
as it doesn't create a list in python3

**Comment by ustinov** [comment]
Why won't you use generator expression
''.join(str(n) for n in range(20))

**Comment by afg984** [comment]
I guess it's about preference

I'd use map in this case because the conversion function already exist

If I shall write
map(lambda n: n.height * n.width, rects)
then I would instead write
(n.height * n.width for n in rects)

Still, I believe generator expression is more readable than ``maps

**Comment by varunagrawal** [comment]
I believe the code was written with clarity in mind. Remember, you're experienced with Python that's why you believe map() does the job the best, but what about someone who is just starting out and wants to do the same? He/She may be a beginner programmer and the concept of _maps_ may be completely alien to them. We don't want to scare people off. :no_good:

**Comment by afg984** [comment]
good point there :P

**Comment by varunagrawal** [comment]
I guess if we have a consensus on understanding, we can close this issue?

**Comment by afg984** [comment]
OK
