### ISSUE TITLE
Remove "Learn Python the Hard Way" from the list

### ISSUE THREAD

**Issue by ewjoachim** [kennethreitz/python-guide#769]
This is, of course, completely up for discussion, but should this project be benefiting an author who is actively participating in (as far as I can tell) harming the community ? (I'm talking about [this](https://learnpythonthehardway.org/book/nopython3.html))

My **personal opinion** would be : his website would be really far down the list of places I'd send someone to learn python with confidence.

Am I the only one ?

**Comment by kennethreitz** [comment]
I think Zed's opinion is his opinion — and LPTHW is one of the best resources around for learning Python today.

**Comment by Seraf69** [comment]
**Important: I do not know Zed in person and I am (still) a novice Pythonista supporting 3.**

Zed is a knowledgeable expert and his post is full of wisdom, assuming one can see beyond his "opinionated" writing style. I disagree with his view, but respect his opinion from where he stands. I don't believe he is "harming the community" because we are much stronger than a single person's view or agenda. Within a healthy and strong community, such criticism should be feedback for the Python 3 developers and supporters to improve it even faster.  

Before anyone argues to ostracize Zed on the basis of one view, please listen to these two excellent interviews, so that you can understand where he is coming from: 
http://www.codenewbie.org/podcast/the-hard-way
http://hanselminutes.com/407/learning-code-the-hard-way-with-zed-shaw

**Comment by ewjoachim** [comment]
Ok, well, that's settled then :) I withdraw my suggestion.

**Comment by hekevintran** [comment]
@ewjoachim So basically you think harming the community involves saying things that are true and pointing out the serious mistakes in Python 3.  You are 100% wrong.  I'd even say that your attempt to shut down a man for telling the truth is very harmful to the community.

Here's the proof, why don't you answer Zed's question that no Python project members can answer since their position is based on a lie: **Why is it impossible for Python 3 to run Python 2 code?**

**Comment by ewjoachim** [comment]
The question at hand is closed. I'd be happy to discuss it on [Twitter](https://twitter.com/ewjoachim) with you if you want.
