### ISSUE TITLE
Dead link: Learning Python section > Magic Methods

### ISSUE THREAD

**Issue by ProfNandaa** [kennethreitz/python-guide#771]
The link at the [_Guide to Python Magic Methods_](http://docs.python-guide.org/en/latest/intro/learning/#a-guide-to-python-s-magic-methods) section is dead - http://www.rafekettler.com/magicmethods.html, or was it momentarily? We might want to update with an alternative...

**Comment by alexholoo** [comment]
Hi @ProfNandaa here is the file: https://github.com/RafeKettler/magicmethods/blob/master/magicmethods.pdf
The link in the Python Guide book is dead because the website is down currently. Here is why if you want to know:  https://github.com/RafeKettler/magicmethods/issues/55

BTW, I made a PR on this issue. If everything is okay, it will be updated soon I guess.  :)

**Comment by ProfNandaa** [comment]
Good stuff @alexholoo -- it's actually merged (4 hrs ago) - #774, thanks!
